In [2]:
#7. mathematical operations on array

In [3]:
import numpy as np
a = np.array([10,20,40,-30])
print(a)

print(a+10)  #add
print(a-30)  #subs
print(a*2)  # multiply
print(a/10) # divide

[ 10  20  40 -30]
[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]
